# Generated by Django 3.2.12 on 2022-07-06 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Naissance')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Décès')),
                ('hyper', models.URLField(blank=True, null=True, verbose_name='Hyperlien')),
            ],
            options={
                'verbose_name': 'Auteur',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Une courte description du livre', max_length=1000, verbose_name='Sommaire')),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn"> ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('apprenti', models.BooleanField(null=True)),
                ('compagnon', models.BooleanField(null=True)),
                ('maitre', models.BooleanField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.author', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Livre',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section principale', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sous-section', max_length=100, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='catalog.section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifiant unique', primary_key=True, serialize=False)),
                ('seq', models.IntegerField(unique=True)),
                ('don', models.BooleanField(null=True)),
                ('new', models.BooleanField(null=True)),
                ('imprint', models.CharField(max_length=200, verbose_name='Édition')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('i', 'Inactif'), ('p', 'Prêté'), ('d', 'Disponible'), ('r', 'Reservé'), ('a', 'À Vendre'), ('v', 'Vendu')], default='d', help_text="Disponibilité de l'exemplaire", max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='Livre')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set Book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this comment', primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Commentaire')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='Livre')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['writer'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec', to='catalog.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='book',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsec', to='catalog.subsection', verbose_name='Subsection'),
        ),
    ]
